a = input('digite algo: ')
print(f'o tipo primitivo desse valor é {type (a)}')
print(f'é alfabético? {a.isalpha()}')
print(f'é númerico? {a.isnumeric()}')
print(f'é alfanumérico? {a.isalnum()}')
print(f'só tem espaços? {a.isspace()}')
print(f'está escrito somente em maiúsculas? {a.isupper()}')
print(f'está escrito somente em minúsculas? {a.islower()}')
print(f'está capitalizada? {a.istitle()}')
