v = float(input('digite um valor em metros: '))
print(f'a medida de {v}m corresponde a: ')
print(f'em KM: {v / 1000}')
print(f'em HM: {v / 100}')
print(f'em DAM: {v / 10}')
print(f'em DM: {v * 10}')
print(f'em CM: {v * 100}')
print(f'em MM: {v * 1000}')
